apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-app
  template:
    metadata:
      labels:
        app: ubuntu-app
    spec:
      nodeSelector:
        role: apps # ensures it runs on app nodes
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]

          # 🔥 THIS IS WHAT YOU NEED
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
