kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: monitoring-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090
        hostPort: 30090
      - containerPort: 30300
        hostPort: 30300

  - role: worker
    labels:
      role: monitoring
  - role: worker
    labels:
      role: apps
  - role: worker
    labels:
      role: apps
